name: Redis
main: com.lith.redis.Plugin

version: 0.0.3
api-version: 1.20

description: A Redis Core plugin for MineCraft plugins
author: Lith
website: https://github.com/ImLith/MC-Redis

depend: [LithCore]
softdepend: []
